USE DesignPatterns;

CREATE TABLE Beer (BeerId INT PRIMARY KEY IDENTITY NOT NULL, NAME VARCHAR(20) NOT NULL, Style VARCHAR(20));

CREATE TABLE Brand (BrandId INT PRIMARY KEY IDENTITY NOT NULL, NAME VARCHAR(30));